name: Build APK and web workflow

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build_apk:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: "11"
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: "3.16.0"
    - name: Clean flutter
      run: flutter clean
    - name: Clean pub cache
      run: flutter pub cache clean
    - name: Get dependencies
      run: flutter pub upgrade
    - name: Run build runner
      run: flutter pub run build_runner build --delete-conflicting-outputs
    - name: Start release android build
      run: flutter build apk --target-platform android-arm,android-arm64
    - name: Upload debug APK to Github Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: otosoft-apk
        path: ${{steps.sign_app.outputs.signedReleaseFile}}
        retention-days: 3
